# Generated by Django 5.1.1 on 2024-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettiApp', '0003_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
